[package]
name = "cellular_raza-concepts"
description = "cellular_raza concepts"
readme = "README.md"
version.workspace = true
authors.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
num = { workspace = true }
serde = { workspace = true }
rand_chacha = { workspace = true }
plotters = { workspace = true }

[dev-dependencies]
rand = { workspace = true }

[features]
default = ["fluid_mechanics", "gradients"]

# Simulation aspects
fluid_mechanics = []
gradients = ["fluid_mechanics"]
