[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[project]
name = "autophagy_pyo3"
version = "0.1.0"

[project.optional-dependencies]
dev = ["pytest"]

[tool.pytest.ini_options]
addopts = "--benchmark-disable"
