[package]
name = "cellular_raza"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "template2"


[dependencies]
nalgebra = { version="0.31" }
ode_integrate = { version="0.0.2" }
rand = { version="0.8", features = ["small_rng"] }
rand_chacha = { version="0.3.1" }
itertools = { version="0.10" }
ndarray = { version="0.15" }
plotters = { version="0.3" }
crossbeam-channel = { version="0.5" }
hurdles = { version="1.0" }
num = { version="0.4" }
uuid = { version="1.2" }
