[package]
name = "cellular_control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "template"


[dependencies]
nalgebra = { version="0.31" }
serde = { version="1.0", features = ["derive"] }
ode_integrate = { version="0.0.2" }
rand = { version="0.8", features = ["small_rng"] }
rand_chacha = { version="0.3.1" }
