[package]
authors = ["Jonas Pleyer <jonas.pleyer@fdm.uni-freiburg.de>"]
name = "cellular_raza"
version = "0.0.2"
edition = "2021"
license = "GPL-2.0"
description = "Cellular simulation tool"
readme = "README.md"
repository = "https://github.com/jonaspleyer/cellular_raza"
keywords = ["cell", "cellular", "simulation"]
categories = ["science", "mathematics", "simulation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
# Core
crossbeam-channel = { version="0.5" }
hurdles = { version="1.0" }
itertools = { version="0.10" }
num = { version="0.4" }
ode_integrate = { version="0.0.2" }
plotters = { version="0.3" }
rayon = { version="1.6" }
uuid = { version="1.2", features=["serde","v4"] }
indicatif = { version="0.17", features=["rayon"] }

# Database
bincode = "1.3"
serde = "1.0"
sled = { version="0.34", optional=true }
typed-sled = { version="0.2", optional=true }
chrono = "0.4"
async-std = "1.12"

# Implementation dependencies
nalgebra = { version="0.32", features=["serde-serialize"]}
rand = { version="0.8", features = ["small_rng"] }
rand_chacha = { version="0.3.1", features=["serde1"]}
ndarray = { version="0.15" }


[dev-dependencies]


[features]
default = ["db_sled"]

# Database
no_db = []
db_sled = ["dep:sled", "dep:typed-sled"]
db_json_dump = []
# Disable features
no_fluid_mechanics = []
no_gradients = []

# Testing
test_exhaustive = []


[profile.release]
debug = 1


[[example]]
name = "kidney_organoid_model"
path = "examples/kidney_organoid_model/src/main.rs"

[[example]]
name = "ureter_signalling"
path = "examples/ureter_signalling/src/main.rs"

[[example]]
name = "ureter_signalling_plot_from_saved_run"
path = "examples/ureter_signalling/src/plot_from_saved_run.rs"
