[workspace]
members = [
    "cellular_raza-benchmarks",
    "cellular_raza-concepts",
    "cellular_raza-core",
    "cellular_raza-core-proc-macro",
    "cellular_raza-building-blocks",
    "cellular_raza-examples/*",
]
resolver = "2"

[workspace.package]
version = "0.0.6"
authors = ["Jonas Pleyer <jonas.dev@pleyer.org>"]
edition = "2021"
license = "GPL-2.0"
repository = "https://github.com/jonaspleyer/cellular_raza"
keywords = ["cell", "cellular", "simulation"]
categories = ["science", "mathematics", "simulation"]
homepage = "https://cellular-raza.com/"

[workspace.dependencies]
num = "0.4"
itertools = "0.12"
plotters = "0.3"
rand = { version="0.8", features = ["small_rng"] }
rand_chacha = { version="0.3.1", features=["serde1"] }
serde = "1.0"
