edition = "2021"
fn_params_layout = "Tall"
hard_tabs = false
max_width = 100
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
