[package]
authors = ["Jonas Pleyer <jonas.pleyer@fdm.uni-freiburg.de>"]
name = "cellular_raza"
version.workspace = true
edition = "2021"
license = "GPL-2.0"
description = "Cellular simulation tool"
readme = "README.md"
repository = "https://github.com/jonaspleyer/cellular_raza"
keywords = ["cell", "cellular", "simulation"]
categories = ["science", "mathematics", "simulation"]
autoexamples = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies.cellular_raza-core]
path = "../cellular_raza-core"
version = "0.0.3"

[dependencies.cellular_raza-building-blocks]
path = "../cellular_raza-building-blocks"
version = "0.0.3"

[dependencies.cellular_raza-concepts]
path = "../cellular_raza-concepts"
version = "0.0.3"

[dependencies.cellular_raza-concepts-derive]
path = "../cellular_raza-concepts-derive"
version = "0.0.3"

[features]
default = ["fluid_mechanics", "gradients"]

# Simulation aspects
fluid_mechanics = []
gradients = ["fluid_mechanics"]
