[package]
name = "cellular_raza-core"
description = "Cellular simulation tool"
readme = "README.md"
documentation = "https://docs.rs/cellular_raza-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
autoexamples = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
# Core
crossbeam-channel = { version="0.5" }
hurdles = { version="1.0" }
itertools = { workspace = true }
num = { workspace = true }
# ode_integrate = { version="0.0.2" }
plotters = { workspace = true }
rayon = { version="1.6" }
indicatif = { version="0.17", features=["rayon"] }

# Storage
bincode = "1.3"
serde = "1.0"
quick-xml = { version="0.28", features=["serialize"]}
serde_json = { version="1.0" }
sled = { version="0.34" }
chrono = "0.4"

# Implementation dependencies
rand = { workspace = true }
rand_chacha = { workspace = true }
# ndarray = { version="0.15", features=["serde"]}

[dependencies.cellular_raza-concepts]
path = "../cellular_raza-concepts"
version = "0.0.3"

[features]
default = ["fluid_mechanics", "gradients"]

# Simulation aspects
fluid_mechanics = []
gradients = ["fluid_mechanics"]

# [profile.release]
# debug = 1
