[package]
name = "cellular_raza-benchmarks"
description = "cellular_raza benchmarks"
readme = "README.md"
version.workspace = true
authors.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
autoexamples = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rand = { version="0.8", features = ["small_rng"] }
rand_chacha = { version="0.3.1", features=["serde1"]}
nalgebra = { version="0.32", features=["serde-serialize"]}
serde = "1.0"
num = "0.4"
criterion = { version = "0.4", features = ["html_reports"] }

[dependencies.cellular_raza]
path = "../cellular_raza"

[features]
default = ["fluid_mechanics", "gradients"]

# Simulation aspects
fluid_mechanics = []
gradients = ["fluid_mechanics"]

[[bench]]
name = "cell_sorting"
harness = false
