[package]
authors = ["Jonas Pleyer <jonas.pleyer@fdm.uni-freiburg.de>"]
name = "cellular_raza-benchmarks"
version = "0.0.3"
edition = "2021"
license = "GPL-2.0"
description = "cellular_raza benchmarks"
readme = "README.md"
repository = "https://github.com/jonaspleyer/cellular_raza"
keywords = ["cell", "cellular", "simulation"]
categories = ["science", "mathematics", "simulation"]
autoexamples = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rand = { version="0.8", features = ["small_rng"] }
rand_chacha = { version="0.3.1", features=["serde1"]}
nalgebra = { version="0.32", features=["serde-serialize"]}
serde = "1.0"
num = "0.4"
criterion = { version = "0.4", features = ["html_reports"] }

[dependencies.cellular_raza]
path = "../cellular_raza"

[features]
default = ["fluid_mechanics", "gradients"]

# Simulation aspects
fluid_mechanics = []
gradients = ["fluid_mechanics"]

[[bench]]
name = "cell_sorting"
harness = false
