[package]
name = "cellular_raza-building-blocks"
description = "cellular_raza Building Blocks"
readme = "README.md"
documentation = "https://docs.rs/cellular_raza-building-blocks"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
plotters = { version="0.3" }
num = "0.4"
rand = { version="0.8", features = ["small_rng"] }
rand_distr = { version="0.4", features = ["serde1"]}
rand_chacha = { version="0.3.1", features=["serde1"]}
nalgebra = { version="0.32", features=["serde-serialize"]}
serde = "1.0"
itertools = { version="0.10" }
rayon = { version="1.6" }

[dependencies.cellular_raza-core]
path = "../cellular_raza-core"
version = "0.0.3"

[dependencies.cellular_raza-concepts]
path = "../cellular_raza-concepts"
version = "0.0.3"

[dependencies.cellular_raza-concepts-derive]
path = "../cellular_raza-concepts-derive"
version = "0.0.3"

[features]
default = ["gradients"]

# Simulation aspects
gradients = []
